### ISSUE TITLE
Problem with the website's theme toggler

### ISSUE THREAD

**Issue by Prashoon123** [discordjs/website#108]
## When the website is in dark mode -
![image](https://user-images.githubusercontent.com/64588766/136694015-127cba7b-9687-4c00-af36-bbb53678f336.png)

## When the website is in light mode -
![image](https://user-images.githubusercontent.com/64588766/136694027-0c8146a1-ea85-4b7b-9010-6c04c988a674.png)

**Comment by Prashoon123** [comment]
@almostSouji But the other maintainer was saying that the symbols shall be swaped. 
![image](https://user-images.githubusercontent.com/64588766/136694714-f7c4a1e1-4856-4a6b-882a-97ad8034482f.png)

**Comment by ImRodry** [comment]
I am not a maintainer, I'm just a regular user like you
