### ISSUE TITLE
Use the new link to @discordjs/voice

### ISSUE THREAD

**Issue by vitorlops** [discordjs/website#118]
Change the last item in the list ([@discordjs/voice](https://github.com/discordjs/voice)) for the new link ([@discordjs/voice](https://github.com/discordjs/discord.js/tree/main/packages/voice)). It is in [welcome page](https://discord.js.org/#/docs/main/stable/general/welcome).
![image](https://user-images.githubusercontent.com/79790819/148692750-9e7ebc01-00a9-4fc5-bcd4-ebb81c48a949.png)

**Comment by iCrawl** [comment]
Nothing to do with this repo.

**Comment by vitorlops** [comment]
Sorry, should I open another issue in [docs repository](https://github.com/discordjs/docs)?

**Comment by almeidx** [comment]
https://github.com/discordjs/discord.js/pull/7229

**Comment by vitorlops** [comment]
I had no idea that it was in discord.js repository, I am sorry.
