### ISSUE TITLE
update the documentation pages

### ISSUE THREAD

**Issue by modernNeo** [discordjs/website#124]
The documentation page is apparently very outdated according to Benjamin Kirby and should really be updated or removed.

**Comment by ImRodry** [comment]
according to who? What page? What package? What?

**Comment by modernNeo** [comment]
for starters, Commando is no longer the official command framework for discordjs, despite what this page claims: https://discord.js.org/#/docs/commando/master/general/welcome

the slash command builders example on this page https://discord.js.org/#/docs/builders/stable/general/welcome links to a non-existent page: https://discord.js.org/docs/examples/Slash%20Command%20Builders.md#/

there are other examples of outdated links on some other pages too, one of them is https://discord.js.org/docs/examples/Slash%20Command%20Builders.md#/docs/builders/stable/class/SlashCommandBooleanOption

and Benjamin Kirby stated on the discord support guild that the documentation page is old:
![Screenshot from 2022-04-14 14-53-21](https://user-images.githubusercontent.com/14242088/163482787-8d5311c6-08c9-488a-b4e0-2f19e050a7db.png)

**Comment by ImRodry** [comment]
So you picked what a random user said out of context and made an issue, congrats

Commando is no longer maintained afaik so if anything it should be removed
builders hasn't had a stable release in a while, so you should be looking at the master branch docs
And that link you sent with the examples works fine to me, don't know what you're talking about.

Either way this isn't a website issue, it's just a matter of using the correct branch and waiting for a stable release of the packages you want

**Comment by modernNeo** [comment]
>So you picked what a random user said out of context and made an issue, congrats

Don't really appreciate the dismissive nature of what you are saying. I did not create this issue because of what that individual said. On the off-chance, they were someone important to the community, i figured what they said mattered. And if they don't matter, that did not change the udnerlying issue I am addressing.

>Commando is no longer maintained afaik so if anything it should be removed

That is what I am suggesting to do.

> builders hasn't had a stable release in a while, so you should be looking at the master branch docs

if that is the case, then the documentation link from the https://discordjs.guide/#before-you-begin should go to https://discord.js.org/#/docs/discord.js/main/general/welcome instead of https://discord.js.org/#/docs/main/stable/general/welcome

**Comment by modernNeo** [comment]
and I would further note that the documentation automatically switches the branch to stable when you flip between `Discord` vs `Collection` vs `Builders` in the menu on the top-left.

**Comment by iCrawl** [comment]
The documentation now defaults to `main` (which is also not 100% desirable) but for now its the best solution until we rewrite it for the logic parts to solve it and jump to the latest release instead.

**Comment by modernNeo** [comment]
@iCrawl it does not. the link on https://discordjs.guide/#before-you-begin still directs to https://discord.js.org/#/docs/main/stable/general/welcome

and also, switching the different pages does not switch the user to `main`.

also, I also brought up the fact that that documentation needs to link to Sapphire instead of Commando, which is not currently the case as far as I can tell?

**Comment by iCrawl** [comment]
This should be brought up to the guide then 👍 

Commando is no longer available as a selection in the docs, Sapphire have their own docs, when we do a formal announcement we will have a placement for linking to it.

**Comment by modernNeo** [comment]
can you direct me to the repo for the guide?

**Comment by iCrawl** [comment]
https://github.com/discordjs/guide
