### ISSUE TITLE
docs down??

### ISSUE THREAD

**Issue by catweaselirl** [discordjs/website#125]
sorry if im a moron... but i cant seem to load the docs? on two seperate pcs and browser, on my phone, and my friend cant load them either. is it down?

**Comment by Prorickey** [comment]
It seems to be down for me too, nothing will load in.

**Comment by Prorickey** [comment]
Yes, they have been down. If you need to use them use https://discordjs-docs.netlify.app/#/docs/discord.js/stable/general/welcome
