### ISSUE TITLE
Example code in collections doc shows backticks

### ISSUE THREAD

**Issue by MajesticString** [discordjs/website#133]
Under the @discordjs/collection docs, when there is an example, the backticks still show:
https://discord.js.org/#/docs/collection/main/class/Collection?scrollTo=each
![image](https://user-images.githubusercontent.com/66224939/179368720-7d8d8ac5-7bd4-4b63-8c5f-8d71a458e159.png)

**Comment by iCrawl** [comment]
Should be fixed in the latest deployment.
