### ISSUE TITLE
Dynamically direct GitHub anchor to current page

### ISSUE THREAD

**Issue by KonkenBonken** [discordjs/website#136]
Now when you click the `GitHub` button in the header it links you to [GitHub/discordjs/discord.js](https://github.com/discordjs/discord.js)
Wouldn't it be much more useful to dynamically change the anchor to link you to the current page you're in
If I would be on [Guild](https://discord.js.org/#/docs/discord.js/stable/class/Guild) it would link to [structures/Guild.js](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/structures/Guild.js)
I've noticed this and think it's anoying that it's not this way. It's way more complicated to navigate from the [root](https://github.com/discordjs/discord.js) to [structures/Guild.js](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/structures/Guild.js) than from [structures/Guild.js](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/structures/Guild.js) to [root](https://github.com/discordjs/discord.js)
![image](https://user-images.githubusercontent.com/49250602/180657953-1f403d78-b759-42d7-b277-1421b10d53c1.png)

**Comment by ImRodry** [comment]
I present to you this neat little button
![D6863299-6475-4CB9-AD91-A6A5B52AF992](https://user-images.githubusercontent.com/38259440/180659765-6d593391-c1a2-4118-9d8a-0405f3c37e5b.jpeg)

**Comment by KonkenBonken** [comment]
@ImRodry Oh...
Totally missed that

**Comment by KonkenBonken** [comment]
@ImRodry Oh...
Totally missed that
