### ISSUE TITLE
invalid link on page

### ISSUE THREAD

**Issue by modernNeo** [discordjs/website#144]
if I go to https://discord.js.org/#/docs/builders/stable/general/welcome

There is the following link:

> Here are some examples for the builders and utilities you can find in this package:
>    [Slash Command Builders](https://discord.js.org/docs/examples/Slash%20Command%20Builders.md)

But as far as I can tell, that page does not exist?

**Comment by Jiralite** [comment]
We're slowly moving away from this website to https://discordjs.dev/.

You can head to https://discordjs.dev/docs/packages/builders/stable and find the working link.
