### ISSUE TITLE
Consider adjusting color a bit?

### ISSUE THREAD

**Issue by elenakrittik** [discordjs/website#151]
The color of new main page's "most popular" label and top note kills my eyes, almost like the plain blue color (`rgb(0, 0, 255)`). I know this is *extremely* opinionated, but may it be possible to adjust this color to, e.g., `rgb(37, 48, 153)` or old "main" color (`rgb(48, 57, 149)`)? Screenshots attached for ease of preview.

Updated color:
![Updated color](https://github.com/discordjs/website/assets/77104725/aa25d89e-0312-4016-8022-389f75d89e9e)

Current color:
![Current color](https://github.com/discordjs/website/assets/77104725/d62a0d3e-b000-4e0d-867e-bcf6ee15a93a)

**Comment by iCrawl** [comment]
That's likely your DarkReader extension. We support native dark mode.

![image](https://github.com/discordjs/website/assets/20760160/61f63a5b-4f91-47f9-baa4-c54630800a8d)

**Comment by elenakrittik** [comment]
OHHH you're actually right, sorry! Completely forgot about it.. The colors look great now, sorry again!
