### ISSUE TITLE
No docs for BaseCollection on master

### ISSUE THREAD

**Issue by kav2k** [discordjs/website#41]
Since `Collection` on master branch now relies on `BaseCollection` from `@discordjs/collection`, the documentation points to supposed docs for that: https://discord.js.org/#/docs/collection (see https://github.com/discordjs/discord.js/blob/master/src/util/Collection.js#L21)

However, that documentation isn't generated / published and so it just redirects to docs homepage.

**Comment by iCrawl** [comment]
This works absolutely fine, make sure your cache is not preventing you from accessing it 
![image](https://user-images.githubusercontent.com/20760160/67383493-8874df80-f58f-11e9-8691-b257fdd4531b.png)

**Comment by kav2k** [comment]
Needed to empty my cache for it to work. Apologies. But it's not obvious for a user.

**Comment by kav2k** [comment]
Actually, clearing _just_ Chrome cache didn't work well. I had to go to the Application tab of the devtools and nuke everything to get it to stick.

There may be a need for some cache invalidation mechanism on the site..
