### ISSUE TITLE
Option to disable realtime search

### ISSUE THREAD

**Issue by ha6000** [discordjs/website#48]
A option that will disable realtime search and it will only goto search page when you hit enter

**Comment by ItsPapaia** [comment]
and what would the option be? how could one decide their preferred behavior? what is your intention anyway?

**Comment by KaKi87** [comment]
Hello, I'd suggest a timeout instead, because it is true that re-searching at every character typed causes the website to lag a bit.
Thanks !

**Comment by tipakA** [comment]
There already is a timeout.

**Comment by KaKi87** [comment]
I see. But it should not be just a simple timeout but a timeout that detects when the user stopped typing.
Like this : https://jsfiddle.net/francescov/FYkYE/

**Comment by pizzafox** [comment]
This is called debouncing. There are npm packages for Vue that do it.

**Comment by KaKi87** [comment]
Fixed by b304c59. Thanks
