### ISSUE TITLE
How create NPM Package with the same style as discordjs website

### ISSUE THREAD

**Issue by Adoums** [discordjs/website#58]
Hi, I've a question,

Have you got an explicative video that explain how create any npm package website docs with th same style as Discordjs website.

Or a website for learn how.

**Comment by kyranet** [comment]
No, we don't. The usual way to do this is by forking the repository (using the Fork button at the top right) and change anything discord.js specific to your own, you must also adopt the [docsgen](https://github.com/discordjs/docgen) in your projects.
