### ISSUE TITLE
Suggestion: create a PR on awesome vite to reference this template

### ISSUE THREAD

**Issue by userquin** [discordjs/website#67]
https://github.com/vitejs/awesome-vite

**Comment by iCrawl** [comment]
This isn't really a template more so than our website/custom documentation 👍

**Comment by userquin** [comment]
upps, the readme file contains this: `This template should help get you started developing with Vue 3 and Typescript in Vite.`...

**Comment by iCrawl** [comment]
Yeah I should probably change that to "How to setup your enviroment" or something along those lines 😅
